version: "3.9"
services:
  dynamodb-local:
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    image: "amazon/dynamodb-local:latest"
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    volumes:
      - "./docker/dynamodb:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal
  oneid-ecs-core:
    build:
      context: ../
      dockerfile: oneid-ecs-core/Dockerfile
      args:
        ENVIRONMENT: dev
    container_name: oneid-ecs-core
    ports:
      - "8080:8080"
    depends_on:
      - "dynamodb-local"
    links:
      - "dynamodb-local"
    environment:
      AWS_ACCESS_KEY_ID: "DUMMYIDEXAMPLE"
      AWS_SECRET_ACCESS_KEY: "DUMMYEXAMPLEKEY"
      REGION: "eu-south-1"
  spid-saml-check:
    image: "italia/spid-saml-check:1.10.6"
    ports:
      - "8443:8443"
