name: OneID FE CI

on:
  push:
    branches:
      - "main"
      - "dev"
    paths:
      - "**/src/oneid/oneid-ecs-core/src/main/webui**"
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8
        with:
          node-version: ${{ matrix.node-version }}
      - name: Run yarn install, lint and test
        working-directory: src/oneid/oneid-ecs-core/src/main/webui
        run: |
          yarn install --frozen-lockfile
          yarn lint
          yarn test
